### ISSUE TITLE
您好 请教一个问题 "找不到项目配置文件config/index，请确定当前目录是Taro项目根目录!"

### ISSUE THREAD

**Issue by gz-sky** [yidierh/mini-bookkeeping#30]
您好 我在编译的时候  一直报错"找不到项目配置文件config/index，请确定当前目录是Taro项目根目录!",是什么原因呢?作为您忠实的粉丝,可否回答一下

**Comment by yidierh** [comment]
开发时，进入 client 目录，在此目录下运行相关编译预览或打包命令
使用微信开发者工具调试项目，请将项目 **整个文件夹** 作为运行目录。 **注意**： 不是 client 中生成的 dist 文件夹

**Comment by yidierh** [comment]
> 您好我在编译的时候一直报错“找到项目配置文件config / index，请确定当前目录是Taro项目根目录！”，是什么原因呢？作为您忠实的粉丝，可否回答一下

开发时，进入 client 目录，在此目录下运行相关编译预览或打包命令
使用微信开发者工具调试项目，请将项目 整个文件夹 作为运行目录。 注意： 不是 client 中生成的 dist 文件夹

**Comment by gz-sky** [comment]
您好 ,非常感谢你的解答。我按照步骤继续往下进行 遇到如下问题[cid:image001.png@01D67D46.DD031DC0]
| 正在编译...[BABEL] Note: The code generator has deoptimised the styling of "E:/nbyh/mini-bookkeeping/client/src/components/chart/ec-canvas/echarts.js" as it exceeds the max of "500KB".
[BABEL] Note: The code generator has deoptimised the styling of "unknown" as it exceeds the max of "500KB".
🙅   编译失败.

./src/pages/user/userInfo/index.jsx
Module build failed (from ./node_modules/@tarojs/mini-runner/dist/loaders/fileParseLoader.js):
SyntaxError: unknown: Unexpected token (12:18)
  10 |
  11 | class UserInfo extends __BaseComponent {
> 12 |   static $events = ["anonymousFunc0", "anonymousFunc1", "anonymousFunc2"];
     |                   ^
  13 |   $usedState = ["$compid__29", "$compid__30", "$compid__31", "$compid__32", "$compid__33", "$compid__34", "$compid__35", "$compid__36", "userInfo", "openSetting", "logOut", "goAbout"];
  14 |
  15 |   config = {


监听文件修改中...

Cannot read property 'hooks' of undefined


Cannot read property 'hooks' of undefined


(node:9212) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hooks' of undefined
    at Watching.handler (E:\nbyh\mini-bookkeeping\client\node_modules\@tarojs\mini-runner\dist\index.js:50:33)
    at E:\nbyh\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:99:9
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\nbyh\mini-bookkeeping\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (E:\nbyh\mini-bookkeeping\client\node_modules\tapable\lib\Hook.js:154:20)
    at Watching._done (E:\nbyh\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:98:28)
    at E:\nbyh\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:73:19
    at Compiler.emitRecords (E:\nbyh\mini-bookkeeping\client\node_modules\webpack\lib\Compiler.js:499:39)
    at E:\nbyh\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:54:20
    at E:\nbyh\mini-bookkeeping\client\node_modules\webpack\lib\Compiler.js:485:14
    at eval (eval at create (E:\nbyh\mini-bookkeeping\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
    at MiniPlugin.<anonymous> (E:\nbyh\mini-bookkeeping\client\node_modules\@tarojs\mini-runner\dist\plugins\MiniPlugin.js:107:17)
    at Generator.next (<anonymous>)
    at fulfilled (E:\nbyh\mini-bookkeeping\client\node_modules\@tarojs\mini-runner\dist\plugins\MiniPlugin.js:5:58)
(node:9212) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9212) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
PS E:\nbyh\mini-bookkeeping\client>

可否再看一下

**Comment by yidierh** [comment]
> 您好 ,非常感谢你的解答。我按照步骤继续往下进行 遇到如下问题[cid:image001.png@01D67D46.DD031DC0] | 正在编译...[BABEL] Note: The code generator has deoptimised the styling of "E:/nbyh/mini-bookkeeping/client/src/components/chart/ec-canvas/echarts.js" as it exceeds the max of "500KB". [BABEL] Note: The code generator has deoptimised the styling of "unknown" as it exceeds the max of "500KB". 🙅 编译失败. ./src/pages/user/userInfo/index.jsx Module build failed (from ./node_modules/@tarojs/mini-runner/dist/loaders/fileParseLoader.js): SyntaxError: unknown: Unexpected token (12:18) 10 | 11 | class UserInfo extends __BaseComponent {
> 12 | static $events = ["anonymousFunc0", "anonymousFunc1", "anonymousFunc2"];
> | ^ 13 | $usedState = ["$compid__29", "$compid__30", "$compid__31", "$compid__32", "$compid__33", "$compid__34", "$compid__35", "$compid__36", "userInfo", "openSetting", "logOut", "goAbout"]; 14 | 15 | config = { 监听文件修改中... Cannot read property 'hooks' of undefined Cannot read property 'hooks' of undefined (node:9212) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hooks' of undefined at Watching.handler (E:\nbyh\mini-bookkeeping\client\node_modules\@tarojs\mini-runner\dist\index.js:50:33) at E:\nbyh\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:99:9 at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\nbyh\mini-bookkeeping\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1) at AsyncSeriesHook.lazyCompileHook (E:\nbyh\mini-bookkeeping\client\node_modules\tapable\lib\Hook.js:154:20) at Watching._done (E:\nbyh\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:98:28) at E:\nbyh\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:73:19 at Compiler.emitRecords (E:\nbyh\mini-bookkeeping\client\node_modules\webpack\lib\Compiler.js:499:39) at E:\nbyh\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:54:20 at E:\nbyh\mini-bookkeeping\client\node_modules\webpack\lib\Compiler.js:485:14 at eval (eval at create (E:\nbyh\mini-bookkeeping\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1) at MiniPlugin.<anonymous> (E:\nbyh\mini-bookkeeping\client\node_modules\@tarojs\mini-runner\dist\plugins\MiniPlugin.js:107:17) at Generator.next (<anonymous>) at fulfilled (E:\nbyh\mini-bookkeeping\client\node_modules\@tarojs\mini-runner\dist\plugins\MiniPlugin.js:5:58) (node:9212) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) (node:9212) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. PS E:\nbyh\mini-bookkeeping\client> 可否再看一下

你把node_modules删掉重新装下看看，第一个 echarts 那个报错不用管

**Comment by wangguangzhong** [comment]
大神  ，为什么这样呢  您帮忙看看
`./src/pages/user/userInfo/index.jsx
Module build failed (from ./node_modules/@tarojs/mini-runner/dist/loaders/fileParseLoader.js):
SyntaxError: unknown: Unexpected token (12:18)
  10 |
  11 | class UserInfo extends __BaseComponent {
> 12 |   static $events = ["anonymousFunc0", "anonymousFunc1", "anonymousFunc2"];
     |                   ^
  13 |   $usedState = ["$compid__29", "$compid__30", "$compid__31", "$compid__32", "$compid__33", "$compid__34", "$compid__35", "$compid__36", "userInfo", "openSetting", "logOut", "goAbout"];
  14 |
  15 |   config = {


监听文件修改中...

Cannot read property 'hooks' of undefined


Cannot read property 'hooks' of undefined


(node:127932) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hooks' of undefined
    at Watching.handler (E:\mini-bookkeeping\client\node_modules\@tarojs\mini-runner\dist\index.js:50:33)
    at E:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:99:9
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\mini-bookkeeping\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (E:\mini-bookkeeping\client\node_modules\tapable\lib\Hook.js:154:20)
    at Watching._done (E:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:98:28)
    at E:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:73:19
    at Compiler.emitRecords (E:\mini-bookkeeping\client\node_modules\webpack\lib\Compiler.js:499:39)
    at E:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:54:20
    at E:\mini-bookkeeping\client\node_modules\webpack\lib\Compiler.js:485:14
    at eval (eval at create (E:\mini-bookkeeping\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
    at MiniPlugin.<anonymous> (E:\mini-bookkeeping\client\node_modules\@tarojs\mini-runner\dist\plugins\MiniPlugin.js:107:17)
    at Generator.next (<anonymous>)
    at fulfilled (E:\mini-bookkeeping\client\node_modules\@tarojs\mini-runner\dist\plugins\MiniPlugin.js:5:58)
(node:127932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:127932) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by yidierh** [comment]
> 大神 ，为什么这样呢 您帮忙看看
> `./src/pages/user/userInfo/index.jsx
> Module build failed (from ./node_modules/@tarojs/mini-runner/dist/loaders/fileParseLoader.js):
> SyntaxError: unknown: Unexpected token (12:18)
> 10 |
> 11 | class UserInfo extends __BaseComponent {
> 
> > 12 |   static $events = ["anonymousFunc0", "anonymousFunc1", "anonymousFunc2"];
> > |                   ^
> > 13 |   $usedState = ["$compid__29", "$compid__30", "$compid__31", "$compid__32", "$compid__33", "$compid__34", "$compid__35", "$compid__36", "userInfo", "openSetting", "logOut", "goAbout"];
> > 14 |
> > 15 |   config = {
> 
> 监听文件修改中...
> 
> Cannot read property 'hooks' of undefined
> 
> Cannot read property 'hooks' of undefined
> 
> (node:127932) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hooks' of undefined
> at Watching.handler (E:\mini-bookkeeping\client\node_modules@tarojs\mini-runner\dist\index.js:50:33)
> at E:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:99:9
> at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\mini-bookkeeping\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), :24:1)
> at AsyncSeriesHook.lazyCompileHook (E:\mini-bookkeeping\client\node_modules\tapable\lib\Hook.js:154:20)
> at Watching._done (E:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:98:28)
> at E:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:73:19
> at Compiler.emitRecords (E:\mini-bookkeeping\client\node_modules\webpack\lib\Compiler.js:499:39)
> at E:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:54:20
> at E:\mini-bookkeeping\client\node_modules\webpack\lib\Compiler.js:485:14
> at eval (eval at create (E:\mini-bookkeeping\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), :11:1)
> at MiniPlugin. (E:\mini-bookkeeping\client\node_modules@tarojs\mini-runner\dist\plugins\MiniPlugin.js:107:17)
> at Generator.next ()
> at fulfilled (E:\mini-bookkeeping\client\node_modules@tarojs\mini-runner\dist\plugins\MiniPlugin.js:5:58)
> (node:127932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:127932) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`


> 大神 ，为什么这样呢 您帮忙看看
> `./src/pages/user/userInfo/index.jsx
> Module build failed (from ./node_modules/@tarojs/mini-runner/dist/loaders/fileParseLoader.js):
> SyntaxError: unknown: Unexpected token (12:18)
> 10 |
> 11 | class UserInfo extends __BaseComponent {
> 
> > 12 |   static $events = ["anonymousFunc0", "anonymousFunc1", "anonymousFunc2"];
> > |                   ^
> > 13 |   $usedState = ["$compid__29", "$compid__30", "$compid__31", "$compid__32", "$compid__33", "$compid__34", "$compid__35", "$compid__36", "userInfo", "openSetting", "logOut", "goAbout"];
> > 14 |
> > 15 |   config = {
> 
> 监听文件修改中...
> 
> Cannot read property 'hooks' of undefined
> 
> Cannot read property 'hooks' of undefined
> 
> (node:127932) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hooks' of undefined
> at Watching.handler (E:\mini-bookkeeping\client\node_modules@tarojs\mini-runner\dist\index.js:50:33)
> at E:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:99:9
> at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\mini-bookkeeping\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), :24:1)
> at AsyncSeriesHook.lazyCompileHook (E:\mini-bookkeeping\client\node_modules\tapable\lib\Hook.js:154:20)
> at Watching._done (E:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:98:28)
> at E:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:73:19
> at Compiler.emitRecords (E:\mini-bookkeeping\client\node_modules\webpack\lib\Compiler.js:499:39)
> at E:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:54:20
> at E:\mini-bookkeeping\client\node_modules\webpack\lib\Compiler.js:485:14
> at eval (eval at create (E:\mini-bookkeeping\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), :11:1)
> at MiniPlugin. (E:\mini-bookkeeping\client\node_modules@tarojs\mini-runner\dist\plugins\MiniPlugin.js:107:17)
> at Generator.next ()
> at fulfilled (E:\mini-bookkeeping\client\node_modules@tarojs\mini-runner\dist\plugins\MiniPlugin.js:5:58)
> (node:127932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:127932) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

更新一下git pull一下，删掉node_modules，重新安装一下依赖

**Comment by gz-sky** [comment]
./src/pages/user/userInfo/index.jsxs deoptimised the styling of "unknown" as it exceeds the max of "500KB".
Module build failed (from ./node_modules/@tarojs/mini-runner/dist/loaders/fileParseLoader.js):
SyntaxError: unknown: Unexpected token (12:18)
  10 |
  11 | class UserInfo extends __BaseComponent {
> 12 |   static $events = ["anonymousFunc0", "anonymousFunc1", "anonymousFunc2"];
     |                   ^
  13 |   $usedState = ["$compid__29", "$compid__30", "$compid__31", "$compid__32", "$compid__33", "$compid__34", "$compid__35", "$compid__36", "userInfo", "openSetting", "logOut", "goAbout"];
  14 |
  15 |   config = {


监听文件修改中...

Cannot read property 'hooks' of undefined


Cannot read property 'hooks' of undefined


(node:12204) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hooks' of undefined
    at Watching.handler (D:\mini-bookkeeping\client\node_modules\@tarojs\mini-runner\dist\index.js:50:33)
    at D:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:99:9
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\mini-bookkeeping\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (D:\mini-bookkeeping\client\node_modules\tapable\lib\Hook.js:154:20)
    at Watching._done (D:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:98:28)
    at D:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:73:19
    at Compiler.emitRecords (D:\mini-bookkeeping\client\node_modules\webpack\lib\Compiler.js:499:39)
    at D:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:54:20
    at D:\mini-bookkeeping\client\node_modules\webpack\lib\Compiler.js:485:14
    at eval (eval at create (D:\mini-bookkeeping\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
    at MiniPlugin.<anonymous> (D:\mini-bookkeeping\client\node_modules\@tarojs\mini-runner\dist\plugins\MiniPlugin.js:107:17)
    at Generator.next (<anonymous>)
    at fulfilled (D:\mini-bookkeeping\client\node_modules\@tarojs\mini-runner\dist\plugins\MiniPlugin.js:5:58)
(node:12204) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12204) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
大神,我又重新试了一下 还是不行 可以加您微信  方便沟通吗??

**Comment by yidierh** [comment]
> ./src/pages/user/userInfo/index.jsxs deoptimised the styling of "unknown" as it exceeds the max of "500KB".
> Module build failed (from ./node_modules/@tarojs/mini-runner/dist/loaders/fileParseLoader.js):
> SyntaxError: unknown: Unexpected token (12:18)
> 10 |
> 11 | class UserInfo extends __BaseComponent {
> 
> > 12 |   static $events = ["anonymousFunc0", "anonymousFunc1", "anonymousFunc2"];
> > |                   ^
> > 13 |   $usedState = ["$compid__29", "$compid__30", "$compid__31", "$compid__32", "$compid__33", "$compid__34", "$compid__35", "$compid__36", "userInfo", "openSetting", "logOut", "goAbout"];
> > 14 |
> > 15 |   config = {
> 
> 监听文件修改中...
> 
> Cannot read property 'hooks' of undefined
> 
> Cannot read property 'hooks' of undefined
> 
> (node:12204) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hooks' of undefined
> at Watching.handler (D:\mini-bookkeeping\client\node_modules@tarojs\mini-runner\dist\index.js:50:33)
> at D:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:99:9
> at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\mini-bookkeeping\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), :24:1)
> at AsyncSeriesHook.lazyCompileHook (D:\mini-bookkeeping\client\node_modules\tapable\lib\Hook.js:154:20)
> at Watching._done (D:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:98:28)
> at D:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:73:19
> at Compiler.emitRecords (D:\mini-bookkeeping\client\node_modules\webpack\lib\Compiler.js:499:39)
> at D:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:54:20
> at D:\mini-bookkeeping\client\node_modules\webpack\lib\Compiler.js:485:14
> at eval (eval at create (D:\mini-bookkeeping\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), :11:1)
> at MiniPlugin. (D:\mini-bookkeeping\client\node_modules@tarojs\mini-runner\dist\plugins\MiniPlugin.js:107:17)
> at Generator.next ()
> at fulfilled (D:\mini-bookkeeping\client\node_modules@tarojs\mini-runner\dist\plugins\MiniPlugin.js:5:58)
> (node:12204) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:12204) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 大神,我又重新试了一下 还是不行 可以加您微信 方便沟通吗??

更新一下git pull一下，删掉node_modules，重新安装一下依赖

**Comment by gz-sky** [comment]
> > ./src/pages/user/userInfo/index.jsxs deoptimised the styling of "unknown" as it exceeds the max of "500KB".
> > Module build failed (from ./node_modules/@tarojs/mini-runner/dist/loaders/fileParseLoader.js):
> > SyntaxError: unknown: Unexpected token (12:18)
> > 10 |
> > 11 | class UserInfo extends __BaseComponent {
> > > 12 |   static $events = ["anonymousFunc0", "anonymousFunc1", "anonymousFunc2"];
> > > |                   ^
> > > 13 |   $usedState = ["$compid__29", "$compid__30", "$compid__31", "$compid__32", "$compid__33", "$compid__34", "$compid__35", "$compid__36", "userInfo", "openSetting", "logOut", "goAbout"];
> > > 14 |
> > > 15 |   config = {
> > 
> > 
> > 监听文件修改中...
> > Cannot read property 'hooks' of undefined
> > Cannot read property 'hooks' of undefined
> > (node:12204) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hooks' of undefined
> > at Watching.handler (D:\mini-bookkeeping\client\node_modules@tarojs\mini-runner\dist\index.js:50:33)
> > at D:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:99:9
> > at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\mini-bookkeeping\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), :24:1)
> > at AsyncSeriesHook.lazyCompileHook (D:\mini-bookkeeping\client\node_modules\tapable\lib\Hook.js:154:20)
> > at Watching._done (D:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:98:28)
> > at D:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:73:19
> > at Compiler.emitRecords (D:\mini-bookkeeping\client\node_modules\webpack\lib\Compiler.js:499:39)
> > at D:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:54:20
> > at D:\mini-bookkeeping\client\node_modules\webpack\lib\Compiler.js:485:14
> > at eval (eval at create (D:\mini-bookkeeping\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), :11:1)
> > at MiniPlugin. (D:\mini-bookkeeping\client\node_modules@tarojs\mini-runner\dist\plugins\MiniPlugin.js:107:17)
> > at Generator.next ()
> > at fulfilled (D:\mini-bookkeeping\client\node_modules@tarojs\mini-runner\dist\plugins\MiniPlugin.js:5:58)
> > (node:12204) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> > (node:12204) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> > 大神,我又重新试了一下 还是不行 可以加您微信 方便沟通吗??
> 
> 更新一下git pull一下，删掉node_modules，重新安装一下依赖

确实已经git pull 了, 也删掉重新npm 了

**Comment by gz-sky** [comment]
大神,为什么点击开始没有反应呢

**Comment by gz-sky** [comment]
大神  现在是这个问题
VM13:1 MiniProgramError
Cannot read property 'icon' of undefined
TypeError: Cannot read property 'icon' of undefined
    at http://127.0.0.1:27984/appservice/pages/home/HomeHistory/index.js:290:60
    at Array.map (<anonymous>)
    at HomeHistory._createData (http://127.0.0.1:27984/appservice/pages/home/HomeHistory/index.js:268:63)
    at doUpdate (http://127.0.0.1:27984/appservice/vendors.js:2923:28)
    at updateComponent (http://127.0.0.1:27984/appservice/vendors.js:2850:11)
    at rerender (http://127.0.0.1:27984/appservice/vendors.js:3039:13)
    at http://127.0.0.1:27984/appservice/vendors.js:3028:13
    at <api nextTick callback function>
    at http://127.0.0.1:27984/appservice/__dev__/WAService.js:2:122133
    at Function.nu (http://127.0.0.1:27984/appservice/__dev__/WAService.js:2:1284724)

**Comment by yidierh** [comment]
> > > ./src/pages/user/userInfo/index.jsxs deoptimised the styling of "unknown" as it exceeds the max of "500KB".
> > > Module build failed (from ./node_modules/@tarojs/mini-runner/dist/loaders/fileParseLoader.js):
> > > SyntaxError: unknown: Unexpected token (12:18)
> > > 10 |
> > > 11 | class UserInfo extends __BaseComponent {
> > > > 12 |   static $events = ["anonymousFunc0", "anonymousFunc1", "anonymousFunc2"];
> > > > |                   ^
> > > > 13 |   $usedState = ["$compid__29", "$compid__30", "$compid__31", "$compid__32", "$compid__33", "$compid__34", "$compid__35", "$compid__36", "userInfo", "openSetting", "logOut", "goAbout"];
> > > > 14 |
> > > > 15 |   config = {
> > > 
> > > 
> > > 监听文件修改中...
> > > Cannot read property 'hooks' of undefined
> > > Cannot read property 'hooks' of undefined
> > > (node:12204) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hooks' of undefined
> > > at Watching.handler (D:\mini-bookkeeping\client\node_modules@tarojs\mini-runner\dist\index.js:50:33)
> > > at D:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:99:9
> > > at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\mini-bookkeeping\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), :24:1)
> > > at AsyncSeriesHook.lazyCompileHook (D:\mini-bookkeeping\client\node_modules\tapable\lib\Hook.js:154:20)
> > > at Watching._done (D:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:98:28)
> > > at D:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:73:19
> > > at Compiler.emitRecords (D:\mini-bookkeeping\client\node_modules\webpack\lib\Compiler.js:499:39)
> > > at D:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:54:20
> > > at D:\mini-bookkeeping\client\node_modules\webpack\lib\Compiler.js:485:14
> > > at eval (eval at create (D:\mini-bookkeeping\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), :11:1)
> > > at MiniPlugin. (D:\mini-bookkeeping\client\node_modules@tarojs\mini-runner\dist\plugins\MiniPlugin.js:107:17)
> > > at Generator.next ()
> > > at fulfilled (D:\mini-bookkeeping\client\node_modules@tarojs\mini-runner\dist\plugins\MiniPlugin.js:5:58)
> > > (node:12204) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> > > (node:12204) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> > > 大神,我又重新试了一下 还是不行 可以加您微信 方便沟通吗??
> > 
> > 
> > 更新一下git pull一下，删掉node_modules，重新安装一下依赖
> 
> 确实已经git pull 了, 也删掉重新npm 了

运行这条命令 taro update self 2.0.5

**Comment by yidierh** [comment]
> 大神 ，为什么这样呢 您帮忙看看
> `./src/pages/user/userInfo/index.jsx
> Module build failed (from ./node_modules/@tarojs/mini-runner/dist/loaders/fileParseLoader.js):
> SyntaxError: unknown: Unexpected token (12:18)
> 10 |
> 11 | class UserInfo extends __BaseComponent {
> 
> > 12 |   static $events = ["anonymousFunc0", "anonymousFunc1", "anonymousFunc2"];
> > |                   ^
> > 13 |   $usedState = ["$compid__29", "$compid__30", "$compid__31", "$compid__32", "$compid__33", "$compid__34", "$compid__35", "$compid__36", "userInfo", "openSetting", "logOut", "goAbout"];
> > 14 |
> > 15 |   config = {
> 
> 监听文件修改中...
> 
> Cannot read property 'hooks' of undefined
> 
> Cannot read property 'hooks' of undefined
> 
> (node:127932) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hooks' of undefined
> at Watching.handler (E:\mini-bookkeeping\client\node_modules@tarojs\mini-runner\dist\index.js:50:33)
> at E:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:99:9
> at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\mini-bookkeeping\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), :24:1)
> at AsyncSeriesHook.lazyCompileHook (E:\mini-bookkeeping\client\node_modules\tapable\lib\Hook.js:154:20)
> at Watching._done (E:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:98:28)
> at E:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:73:19
> at Compiler.emitRecords (E:\mini-bookkeeping\client\node_modules\webpack\lib\Compiler.js:499:39)
> at E:\mini-bookkeeping\client\node_modules\webpack\lib\Watching.js:54:20
> at E:\mini-bookkeeping\client\node_modules\webpack\lib\Compiler.js:485:14
> at eval (eval at create (E:\mini-bookkeeping\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), :11:1)
> at MiniPlugin. (E:\mini-bookkeeping\client\node_modules@tarojs\mini-runner\dist\plugins\MiniPlugin.js:107:17)
> at Generator.next ()
> at fulfilled (E:\mini-bookkeeping\client\node_modules@tarojs\mini-runner\dist\plugins\MiniPlugin.js:5:58)
> (node:127932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:127932) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

taro update self 2.0.5运行这条命令
