### ISSUE TITLE
大神，编译问题解决了（node v10.15.3  taro 2.0.5）  现在又有新问题

### ISSUE THREAD

**Issue by wangguangzhong** [yidierh/mini-bookkeeping#33]
目前已创建集合‘app’,'bank','record','month_record','day_record',还会出现以下问题 ，login和statistics已经上传和部署
VM418:1 (in promise) MiniProgramError
errCode: -404011 cloud function execution error | errMsg: cloud.callFunction:fail requestID , cloud function service error code -501000, error message Environment not found; at cloud.callFunction api; 
Error: errCode: -404011 cloud function execution error | errMsg: cloud.callFunction:fail requestID , cloud function service error code -501000, error message Environment not found; at cloud.callFunction api; 
    at new u (http://127.0.0.1:29868/appservice/__dev__/WAService.js:2:263619)
    at d (http://127.0.0.1:29868/appservice/__dev__/WAService.js:2:264126)
    at f (http://127.0.0.1:29868/appservice/__dev__/WAService.js:2:264221)
    at Function.success (http://127.0.0.1:29868/appservice/__dev__/WAService.js:2:422832)
    at h (http://127.0.0.1:29868/appservice/__dev__/WAService.js:2:121308)
    at http://127.0.0.1:29868/appservice/__dev__/WAService.js:2:122133
    at A (http://127.0.0.1:29868/appservice/__dev__/WAService.js:2:603030)
    at Function.<anonymous> (http://127.0.0.1:29868/appservice/__dev__/WAService.js:2:805968)
    at h (http://127.0.0.1:29868/appservice/__dev__/WAService.js:2:121308)
    at http://127.0.0.1:29868/appservice/__dev__/WAService.js:2:122133

**Comment by wangguangzhong** [comment]
原先使用taro3.0  由于版本问题 一直报错，现已经解决

**Comment by wangguangzhong** [comment]
cloud.init 也已经设置了
